# https://www.appveyor.com/docs/appveyor-yml

install:
  # Use Python 3.
  - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

build_script:
  - python --version
  - python make_total_membership_csv.py

test: off

artifacts:
  - path: total-membership.csv

skip_tags: true
